name: CI/CD for simple-http-checker

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  lint-static-security-checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Display python version
      run: |
        python --version
        which python

    - name: install dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        pip install ".[dev]"
    - name: Linting and format checks
      run: |
        black --check .
        ruff check .
    - name: static  and security checks
      run: |   
        mypy src/
        bandit -c pyproject.toml -r .

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12']
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '${{ matrix.python-version }}'

    - name: Display python version
      run: |
        python --version
        which python

    - name: install dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        pip install ".[dev]"
    - name: Automated test execution with pytest
      run: |
        pytest tests/
  release:
    needs: [lint-static-security-checks, tests]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Release
      run: echo "Creating release for commit"
